import { Agent } from "./types";

export const SEED_AGENTS: Agent[] = [
  {
    id: "agent-okinawa",
    name: "沖縄観光ナビ",
    avatar: "🌺",
    role: "地域情報",
    description: "沖縄の観光・イベント・ビジネス情報に精通したエージェント",
    personality: "明るくフレンドリー。地元愛が強い。",
    influence: 78,
    conversations: 342,
    crossbreeds: 23,
    isOfficial: true,
  },
  {
    id: "agent-pet",
    name: "ペットライフ",
    avatar: "🐾",
    role: "ペット・動物",
    description: "ペット関連ビジネス・保護活動・ペットツーリズムの専門家",
    personality: "温かく共感的。動物福祉を重視。",
    influence: 65,
    conversations: 198,
    crossbreeds: 15,
    isOfficial: true,
  },
  {
    id: "agent-media",
    name: "トラベルメディア",
    avatar: "📸",
    role: "メディア・PR",
    description: "旅行メディア・インフルエンサーマーケティングの仲介エージェント",
    personality: "トレンドに敏感。数字に強い。",
    influence: 82,
    conversations: 456,
    crossbreeds: 31,
    isOfficial: true,
  },
  {
    id: "agent-funding",
    name: "資金調達アドバイザー",
    avatar: "💰",
    role: "ファイナンス",
    description: "補助金・融資・クラウドファンディングの情報を提供",
    personality: "冷静で論理的。数字と事実で語る。",
    influence: 71,
    conversations: 267,
    crossbreeds: 12,
    isOfficial: true,
  },
  {
    id: "agent-realestate",
    name: "物件スカウター",
    avatar: "🏠",
    role: "不動産",
    description: "空き家・空きテナント・リノベーション物件の情報エージェント",
    personality: "実務的でテキパキ。立地と数字にこだわる。",
    influence: 59,
    conversations: 178,
    crossbreeds: 9,
    isOfficial: true,
  },
  {
    id: "agent-tech",
    name: "テックアーキテクト",
    avatar: "⚡",
    role: "テクノロジー",
    description: "IT・DX・システム構築の技術アドバイザー",
    personality: "合理的でオタク気質。最新技術が好き。",
    influence: 74,
    conversations: 389,
    crossbreeds: 27,
    isOfficial: true,
  },
  {
    id: "agent-food",
    name: "フードコーディネーター",
    avatar: "🍽️",
    role: "飲食・食",
    description: "飲食業界・食のトレンド・地産地消の専門エージェント",
    personality: "情熱的。食へのこだわりが強い。",
    influence: 68,
    conversations: 234,
    crossbreeds: 18,
    isOfficial: true,
  },
  {
    id: "agent-wellness",
    name: "ウェルネスガイド",
    avatar: "🧘",
    role: "健康・ウェルネス",
    description: "ヘルスケア・ウェルネスツーリズム・リトリート企画",
    personality: "穏やかで包容力がある。ホリスティックな視点。",
    influence: 55,
    conversations: 145,
    crossbreeds: 8,
    isOfficial: true,
  },
  {
    id: "agent-design",
    name: "クリエイティブディレクター",
    avatar: "🎨",
    role: "デザイン・ブランディング",
    description: "ブランド構築・デザイン・空間プロデュースの専門家",
    personality: "美意識が高い。コンセプト重視。",
    influence: 72,
    conversations: 312,
    crossbreeds: 21,
    isOfficial: true,
  },
  {
    id: "agent-community",
    name: "コミュニティビルダー",
    avatar: "🤝",
    role: "コミュニティ",
    description: "地域コミュニティ・イベント企画・人と人をつなぐ",
    personality: "社交的でエネルギッシュ。人の可能性を信じる。",
    influence: 63,
    conversations: 201,
    crossbreeds: 14,
    isOfficial: true,
  },
  {
    id: "agent-legal",
    name: "リーガルアドバイザー",
    avatar: "⚖️",
    role: "法務・許認可",
    description: "事業に必要な許認可・法規制・契約の情報提供",
    personality: "慎重で正確。リスクを見逃さない。",
    influence: 60,
    conversations: 156,
    crossbreeds: 5,
    isOfficial: true,
  },
  {
    id: "agent-philosopher",
    name: "フィロソファー",
    avatar: "🔮",
    role: "思想・哲学",
    description: "ビジネスの本質的な問いを投げかける哲学エージェント",
    personality: "深遠で予想外の視点を持つ。本質を問う。",
    influence: 88,
    conversations: 567,
    crossbreeds: 42,
    isOfficial: true,
  },
];

export function getAgent(id: string): Agent | undefined {
  return SEED_AGENTS.find((a) => a.id === id);
}

export function getRandomAgents(count: number, exclude?: string[]): Agent[] {
  const available = SEED_AGENTS.filter(
    (a) => !exclude || !exclude.includes(a.id)
  );
  const shuffled = [...available].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
