import crypto from "crypto";

function getSecret(): string {
  const secret = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!secret) throw new Error("SUPABASE_SERVICE_ROLE_KEY is required for OAuth state signing");
  return secret;
}

/**
 * Create a signed OAuth state parameter with nonce.
 * Prevents CSRF attacks by ensuring the state was generated by our server.
 */
export function createOAuthState(data: Record<string, unknown>): string {
  const nonce = crypto.randomBytes(16).toString("hex");
  const payload = { ...data, nonce, ts: Date.now() };
  const payloadStr = JSON.stringify(payload);
  const signature = crypto
    .createHmac("sha256", getSecret())
    .update(payloadStr)
    .digest("hex");
  return Buffer.from(JSON.stringify({ p: payloadStr, s: signature })).toString("base64url");
}

/**
 * Verify and decode a signed OAuth state parameter.
 * Returns the payload if valid, null if tampered or expired (>10 min).
 */
export function verifyOAuthState(state: string): Record<string, unknown> | null {
  try {
    const { p: payloadStr, s: signature } = JSON.parse(
      Buffer.from(state, "base64url").toString("utf-8"),
    );
    const expected = crypto
      .createHmac("sha256", getSecret())
      .update(payloadStr)
      .digest("hex");
    if (signature !== expected) return null;

    const payload = JSON.parse(payloadStr);

    // Reject states older than 10 minutes
    if (payload.ts && Date.now() - payload.ts > 10 * 60 * 1000) return null;

    return payload;
  } catch {
    return null;
  }
}
